#!/bin/sh

if pgrep -x dwmblocks 2>&1 >/dev/null;
then
	printf "Killing old dwmblocks instances ... "
	pkill -KILL -x dwmblocks
	printf "done.\n"
fi

if [ -e $HOME/.xinitrc ];
then
	cat $HOME/.xinitrc | grep dwmblocks | sh
else
	dwmblocks &
fi

